force-app/main/default/objects/weatherLocation__c/weatherLocation__c.object-meta.xml
<CustomObject>
    <label>weatherLocation</label>
    <nameField>
        <label>weatherLocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>weatherLocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/weatherLocation__c/fields/latitude__c.field-meta.xml
<CustomField>
    <fullName>latitude__c</fullName>
    <label>latitude</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/weatherLocation__c/fields/longitude__c.field-meta.xml
<CustomField>
    <fullName>longitude__c</fullName>
    <label>longitude</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/weatherLWC.cls
public with sharing class weatherLWC {
    @AuraEnabled(cacheable=true)
    public static string call(string lat, string lon, string key) {
        string payload = 'lat=' + lat +
                         '&lon=' + lon + 
                         '&appid=' + key;
        String apiCall = 'http://api.openweathermap.org/data/2.5/onecall?' + payload;
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setTimeout(60000);
        request.setEndpoint(apiCall);
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        String JSON = response.getBody();
        JSON = JSON.replace('1h','h');
        return JSON;
    }

    @AuraEnabled(cacheable=true)
    public static list<weatherLocation__c> pop() {
        list<weatherLocation__c> locations = [SELECT Id, Name, latitude__c, longitude__c FROM weatherLocation__c];
        return locations;

        /*        list<map<string,string>> parsedLocations = new list<map<string,string>>();

        for (weatherLocation__c wl : locations) {
            map<string,string> cur = new map<string,string>();
            cur.put('Id', wl.Id);
            cur.put('Name', wl.Name);
            cur.put('lat', wl.latitude__c);
            cur.put('lon',wl.longitude__c);
            parsedLocations.add(cur);
            system.debug(cur);
        }
        return parsedLocations;*/
    }
}